import React,{createContext,useContext,useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {HashRouter,Routes,Route,Navigate,Link,NavLink,useNavigate,useParams} from 'react-router-dom';
import {Navbar,Container,Nav,Button,Card,Form,Row,Col,Table,Badge,Alert,Modal,InputGroup,Spinner} from 'react-bootstrap';
import 'bootstrap/dist/css/bootstrap.min.css';import './styles.css';

const API='http://localhost:4000/api';
const DEMO_PHOTOS='https://jsonplaceholder.typicode.com/photos';
const DEMO_VIDEO='https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4';

const demoUsers=[
 {id:1,name:'Mark Fishman',email:'manfrozeninaglacierwithnopants@example.com',role:'admin',directories:['Family','Trips','Videos']},
 {id:2,name:'Michael Sackson',email:'big.mike@example.com',role:'user',directories:['Family']},
 {id:3,name:'Ellison Torrez',email:'ellto@example.com',role:'user',directories:['Trips','Videos']}
];
const demoDirectories=[
 {id:1,name:'Family',type:'photos',description:'Family photos'},
 {id:2,name:'Trips',type:'photos',description:'Travel photos'},
 {id:3,name:'Videos',type:'videos',description:'Demo video library'}
];

const AuthContext=createContext(null);
function AuthProvider({children}){
 const [users,setUsers]=useState(()=>JSON.parse(localStorage.getItem('mv-users')||'null')||demoUsers);
 const [currentId,setCurrentId]=useState(()=>Number(localStorage.getItem('mv-current'))||null);
 useEffect(()=>localStorage.setItem('mv-users',JSON.stringify(users)),[users]);
 useEffect(()=>currentId?localStorage.setItem('mv-current',String(currentId)):localStorage.removeItem('mv-current'),[currentId]);
 const currentUser=users.find(u=>u.id===currentId)||null;
 const login=email=>{const u=users.find(x=>x.email.toLowerCase()===email.trim().toLowerCase());if(!u)return false;setCurrentId(u.id);return true};
 const logout=()=>setCurrentId(null);
 return <AuthContext.Provider value={{users,setUsers,currentUser,login,logout}}>{children}</AuthContext.Provider>;
}
const useAuth=()=>useContext(AuthContext);
function Protected({admin=false,children}){const {currentUser}=useAuth();if(!currentUser)return <Navigate to="/login" replace/>;if(admin&&currentUser.role!=='admin')return <Navigate to="/library" replace/>;return children}
function Layout(){const {currentUser,logout}=useAuth();return <><Navbar bg="dark" variant="dark" expand="md" sticky="top"><Container><Navbar.Brand as={Link} to="/">Media Vault</Navbar.Brand><Navbar.Toggle/><Navbar.Collapse><Nav className="me-auto"><Nav.Link as={NavLink} to="/library">Library</Nav.Link>{currentUser?.role==='admin'&&<Nav.Link as={NavLink} to="/admin">Admin</Nav.Link>}</Nav>{currentUser?<><Navbar.Text className="me-3">{currentUser.name}</Navbar.Text><Button size="sm" variant="outline-light" onClick={logout}>Logout</Button></>:<Button as={Link} to="/login" size="sm" variant="outline-light">Login</Button>}</Navbar.Collapse></Container></Navbar><Container className="py-4"><Routes><Route path="/" element={<Home/>}/><Route path="/login" element={<Login/>}/><Route path="/library" element={<Protected><Library/></Protected>}/><Route path="/directory/:name" element={<Protected><Directory/></Protected>}/><Route path="/admin" element={<Protected admin><Admin/></Protected>}/><Route path="*" element={<Navigate to="/" replace/>}/></Routes></Container></>}
function Home(){return <div className="hero p-5 rounded-4"><Badge bg="primary" className="mb-3">React + Bootstrap + React Router + Node + Express + PostgreSQL</Badge><h1>Media Vault</h1><p className="lead">A company-ready demo structure for authenticated media access, admin user management, directory permissions, and future Amazon S3 storage.</p><div className="d-flex gap-2"><Button as={Link} to="/login">Open demo</Button><Button as={Link} to="/library" variant="outline-primary">Library</Button></div><hr/><p className="small mb-0">Demo login: <strong>manfrozeninaglacierwithnopants@example.com</strong>, <strong>big.mike@example.com</strong>, or <strong>ellto@example.com</strong>. The browser demo uses local state; the Express API is provided as the production backend template.</p></div>}
function Login(){const {login,currentUser}=useAuth();const nav=useNavigate();const [email,setEmail]=useState('');const [error,setError]=useState('');if(currentUser)return <Navigate to={currentUser.role==='admin'?'/admin':'/library'} replace/>;function submit(e){e.preventDefault();if(login(email))nav('/library');else setError('Demo user not found. Try admin@example.com.')}return <Row className="justify-content-center"><Col md={6} lg={5}><Card><Card.Body className="p-4"><h2>Sign in</h2><p className="text-secondary">Front-end demo authentication. The backend template includes the real API structure.</p>{error&&<Alert variant="danger">{error}</Alert>}<Form onSubmit={submit}><Form.Group className="mb-3"><Form.Label>Email</Form.Label><Form.Control value={email} onChange={e=>setEmail(e.target.value)} placeholder="admin@example.com" required/></Form.Group><Button type="submit" className="w-100">Sign in</Button></Form></Card.Body></Card></Col></Row>}
function Library(){const {currentUser}=useAuth();const allowed=demoDirectories.filter(d=>currentUser.directories.includes(d.name));return <><div className="d-flex justify-content-between align-items-center mb-4"><div><h2>Your library</h2><p className="text-secondary mb-0">Only your approved directories are displayed.</p></div><Badge bg="secondary">{allowed.length} approved</Badge></div>{!allowed.length?<Alert variant="warning">No directories have been assigned.</Alert>:<Row>{allowed.map(d=><Col md={6} lg={4} className="mb-4" key={d.id}><Card className="h-100"><Card.Body><div className="display-6 mb-3">{d.type==='videos'?'▶':'▣'}</div><Card.Title>{d.name}</Card.Title><Card.Text className="text-secondary">{d.description}</Card.Text><Button as={Link} to={`/directory/${encodeURIComponent(d.name)}`}>Open directory</Button></Card.Body></Card></Col>)}</Row>}</>}
function Directory(){const {name}=useParams();const {currentUser}=useAuth();const directory=demoDirectories.find(d=>d.name===name);if(!directory||!currentUser.directories.includes(name))return <Alert variant="danger">You do not have access to this directory.</Alert>;return directory.type==='videos'?<VideoDirectory/>:<PhotoDirectory albumId={directory.id} name={directory.name}/>}
function PhotoDirectory({albumId,name}){const [photos,setPhotos]=useState([]);const [loading,setLoading]=useState(true);useEffect(()=>{fetch(`${DEMO_PHOTOS}?albumId=${albumId}`).then(r=>r.json()).then(x=>setPhotos(x.slice(0,12))).catch(()=>setPhotos([])).finally(()=>setLoading(false))},[albumId]);return <><h2>{name}</h2><p className="text-secondary">Demo photos from JSONPlaceholder. Replace this adapter with Media Vault's API/S3 media URLs later.</p>{loading?<Spinner/>:<Row>{photos.map(p=><Col sm={6} lg={4} xl={3} className="mb-4" key={p.id}><Card className="h-100"><Card.Img variant="top" src={p.thumbnailUrl} alt={p.title}/><Card.Body><Card.Text className="small">{p.title}</Card.Text></Card.Body></Card></Col>)}</Row>}</>}
function VideoDirectory(){return <><h2>Videos</h2><p className="text-secondary">Demo MP4. The future S3 adapter belongs in the Express backend.</p><Card className="video-card"><Card.Body><video className="w-100 rounded" controls preload="metadata"><source src={DEMO_VIDEO} type="video/mp4"/></video><Card.Title className="mt-3">Demo video</Card.Title></Card.Body></Card></>}
function Admin(){const {users,setUsers}=useAuth();const [editing,setEditing]=useState(null);const [show,setShow]=useState(false);const [search,setSearch]=useState('');const filtered=users.filter(u=>(u.name+' '+u.email).toLowerCase().includes(search.toLowerCase()));function save(user){setUsers(prev=>prev.some(u=>u.id===user.id)?prev.map(u=>u.id===user.id?user:u):[...prev,user]);setShow(false);setEditing(null)}function remove(id){if(window.confirm('Delete this user?'))setUsers(prev=>prev.filter(u=>u.id!==id))}return <><div className="d-flex justify-content-between align-items-center mb-3"><div><h2>Admin</h2><p className="text-secondary mb-0">CRUD users and assign approved directories.</p></div><Button onClick={()=>{setEditing({id:Date.now(),name:'',email:'',role:'user',directories:[]});setShow(true)}}>Add user</Button></div><InputGroup className="mb-3"><InputGroup.Text>Search</InputGroup.Text><Form.Control value={search} onChange={e=>setSearch(e.target.value)} placeholder="Name or email"/></InputGroup><div className="table-responsive"><Table hover bordered><thead><tr><th>User</th><th>Role</th><th>Directory access</th><th/></tr></thead><tbody>{filtered.map(u=><tr key={u.id}><td><strong>{u.name}</strong><div className="small text-secondary">{u.email}</div></td><td><Badge bg={u.role==='admin'?'danger':'secondary'}>{u.role}</Badge></td><td>{u.directories.length?u.directories.map(d=><Badge bg="light" text="dark" className="me-1" key={d}>{d}</Badge>):<span className="text-secondary">None</span>}</td><td className="text-end"><Button size="sm" variant="outline-primary" className="me-2" onClick={()=>{setEditing({...u});setShow(true)}}>Edit</Button><Button size="sm" variant="outline-danger" onClick={()=>remove(u.id)}>Delete</Button></td></tr>)}</tbody></Table></div><UserModal show={show} user={editing} onHide={()=>setShow(false)} onSave={save}/></>}
function UserModal({show,user,onHide,onSave}){const [draft,setDraft]=useState(user);useEffect(()=>setDraft(user),[user]);if(!draft)return null;function toggle(d){setDraft(x=>({...x,directories:x.directories.includes(d)?x.directories.filter(v=>v!==d):[...x.directories,d]}))}return <Modal show={show} onHide={onHide}><Modal.Header closeButton><Modal.Title>{draft.id&&demoUsers.some(u=>u.id===draft.id)?'Edit user':'Add user'}</Modal.Title></Modal.Header><Modal.Body><Form.Group className="mb-3"><Form.Label>Name</Form.Label><Form.Control value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></Form.Group><Form.Group className="mb-3"><Form.Label>Email</Form.Label><Form.Control type="email" value={draft.email} onChange={e=>setDraft({...draft,email:e.target.value})}/></Form.Group><Form.Group className="mb-3"><Form.Label>Role</Form.Label><Form.Select value={draft.role} onChange={e=>setDraft({...draft,role:e.target.value})}><option value="user">User</option><option value="admin">Admin</option></Form.Select></Form.Group><Form.Label>Approved directories</Form.Label>{demoDirectories.map(d=><Form.Check key={d.id} type="checkbox" label={d.name} checked={draft.directories.includes(d.name)} onChange={()=>toggle(d.name)}/>)}</Modal.Body><Modal.Footer><Button variant="secondary" onClick={onHide}>Cancel</Button><Button onClick={()=>onSave(draft)} disabled={!draft.name||!draft.email}>Save</Button></Modal.Footer></Modal>}
function App(){return <AuthProvider><Layout/></AuthProvider>}
createRoot(document.getElementById('root')).render(<HashRouter><App/></HashRouter>);
